/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsNewRouteImport } from './routes/skills/new'
import { Route as SkillsIdRouteImport } from './routes/skills/$id'
import { Route as SkillsIdEditRouteImport } from './routes/skills/$id/edit'
import { Route as _authSignUpSplatRouteImport } from './routes/__auth/sign-up.$'
import { Route as _authSignInSplatRouteImport } from './routes/__auth/sign-in.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/skills/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdEditRoute = SkillsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SkillsIdRoute,
} as any)
const _authSignUpSplatRoute = _authSignUpSplatRouteImport.update({
  id: '/__auth/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const _authSignInSplatRoute = _authSignInSplatRouteImport.update({
  id: '/__auth/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills/$id': typeof SkillsIdRouteWithChildren
  '/skills/new': typeof SkillsNewRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/sign-up/$': typeof _authSignUpSplatRoute
  '/skills/$id/edit': typeof SkillsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills/$id': typeof SkillsIdRouteWithChildren
  '/skills/new': typeof SkillsNewRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/sign-up/$': typeof _authSignUpSplatRoute
  '/skills/$id/edit': typeof SkillsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills/$id': typeof SkillsIdRouteWithChildren
  '/skills/new': typeof SkillsNewRoute
  '/__auth/sign-in/$': typeof _authSignInSplatRoute
  '/__auth/sign-up/$': typeof _authSignUpSplatRoute
  '/skills/$id/edit': typeof SkillsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skills/$id'
    | '/skills/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/skills/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/skills/$id'
    | '/skills/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/skills/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/skills/$id'
    | '/skills/new'
    | '/__auth/sign-in/$'
    | '/__auth/sign-up/$'
    | '/skills/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsIdRoute: typeof SkillsIdRouteWithChildren
  SkillsNewRoute: typeof SkillsNewRoute
  _authSignInSplatRoute: typeof _authSignInSplatRoute
  _authSignUpSplatRoute: typeof _authSignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$id': {
      id: '/skills/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$id/edit': {
      id: '/skills/$id/edit'
      path: '/edit'
      fullPath: '/skills/$id/edit'
      preLoaderRoute: typeof SkillsIdEditRouteImport
      parentRoute: typeof SkillsIdRoute
    }
    '/__auth/sign-up/$': {
      id: '/__auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof _authSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/sign-in/$': {
      id: '/__auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof _authSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SkillsIdRouteChildren {
  SkillsIdEditRoute: typeof SkillsIdEditRoute
}

const SkillsIdRouteChildren: SkillsIdRouteChildren = {
  SkillsIdEditRoute: SkillsIdEditRoute,
}

const SkillsIdRouteWithChildren = SkillsIdRoute._addFileChildren(
  SkillsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsIdRoute: SkillsIdRouteWithChildren,
  SkillsNewRoute: SkillsNewRoute,
  _authSignInSplatRoute: _authSignInSplatRoute,
  _authSignUpSplatRoute: _authSignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
