/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsSlugRouteImport } from './routes/skills/$slug'
import { Route as _authSignUpSplatRouteImport } from './routes/__auth/sign-up.$'
import { Route as _authSignInSplatRouteImport } from './routes/__auth/sign-in.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const _authSignUpSplatRoute = _authSignUpSplatRouteImport.update({
  id: '/__auth/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const _authSignInSplatRoute = _authSignInSplatRouteImport.update({
  id: '/__auth/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/sign-up/$': typeof _authSignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/sign-in/$': typeof _authSignInSplatRoute
  '/sign-up/$': typeof _authSignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/__auth/sign-in/$': typeof _authSignInSplatRoute
  '/__auth/sign-up/$': typeof _authSignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/skills/$slug' | '/sign-in/$' | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/skills/$slug' | '/sign-in/$' | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/skills/$slug'
    | '/__auth/sign-in/$'
    | '/__auth/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
  _authSignInSplatRoute: typeof _authSignInSplatRoute
  _authSignUpSplatRoute: typeof _authSignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/sign-up/$': {
      id: '/__auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof _authSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/sign-in/$': {
      id: '/__auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof _authSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsSlugRoute: SkillsSlugRoute,
  _authSignInSplatRoute: _authSignInSplatRoute,
  _authSignUpSplatRoute: _authSignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
